### ISSUE TITLE
HU05 - Consultar listado de coleccionistas

### ISSUE THREAD

**Issue by ylozadaga** [ylozadaga/vinyls-app#5]
## Detalle

**Cómo** usuario visitante
**Quiero** quiero consultar el listado de coleccionistas
**Para** seleccionar el que más me interese.

## Tareas

 - [x] #16
 - [x] #17
 - [x] #18
 - [ ] #19
 - [ ] #20
 - [ ] #21

**Comment by edwin15torres** [comment]
Se movera esta HU para el siguiente Sprint
