### ISSUE TITLE
HU06 - Consultar la información detallada de coleccionista

### ISSUE THREAD

**Issue by ylozadaga** [ylozadaga/vinyls-app#6]
## Detalle

**Cómo** usuario visitante
**Quiero** ver el detalle de un coleccionista
**Para** conocer sus gustos musicales.

## Tareas

 - [x] #22
 - [x] #23
 - [x] #24
 - [x] #25
 - [ ] #26
 - [x] #27

**Comment by edwin15torres** [comment]
Update milestone
